name: Bump
on:
   push:
      branches: [main]
jobs:
   build:
      name: Release
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v2
           with:
              fetch-depth: 0
         - name: Setup GIT
           run: |
              git switch -c master
              git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
              git config user.name "$GITHUB_ACTOR"

         - name: "Automated Version Bump"
           run: npm version patch

         - name: Update & Push
           env:
              GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
           run: |
              printf "\n\n$(date)" >> README.md
              git add .
              git commit -m "bump version"
              git push origin master:main
