name: Bump
on:
   push:
      branches: [main]
jobs:
   build:
      name: Release
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v2
           with:
              fetch-depth: 0
         - name: "Automated Version Bump"
           run: npm version patch
         - name: "Automated Version Bump"
           run: git add .

         - name: "Automated Version Bump"
           run: git commit -m 'bump'

         - name: "Automated Version Bump"
           run: git push
