name: Bump
on:
   push:
      branches: [main]
jobs:
   build:
      name: Release
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v2
           with:
              fetch-depth: 0
         - name: Setup GIT
           run: |
              git switch -c version-branch
              git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
              git config user.name "$GITHUB_ACTOR"

         - name: "Automated Version Bump"
           run: npm version patch

         - name: Update & Push
           env:
              GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
           run: |
              git add .
              git commit -m "bump version "
              git push origin version-branch:main

         - name: Release
           uses: justincy/github-action-npm-release@2.0.2
           id: release
         - name: Print release output
           if: ${{ steps.release.outputs.released == 'true' }}
           run: echo Release ID ${{ steps.release.outputs.release_id }}

         - name: 🟢 node
           uses: actions/setup-node@v1
           with:
              node-version: 14
              registry-url: https://registry.npmjs.org
         - name: 🚀 ci
           run: npm install
         - name: 🚀 build
           run: npm run build
         - name: 🚀 publish
           run: npm publish --access public
           env:
              NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
