name: Purge Cdn Cache
on:
   workflow_dispatch:
jobs:
   purge-jsdelivr-cache:
      runs-on: ubuntu-20.04
      steps:
         - uses: gacts/purge-jsdelivr-cache@v1
           with:
              url: |
                 https://cdn.jsdelivr.net/npm/jquery@3.2.0/dist/jquery.js
                 https://cdn.jsdelivr.net/npm/jquery@3.3.0/dist/jquery.min.js
