name: Release
on:
   push:
      tags:
         - "*"
jobs:
   release:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@master
         - name: Create Archive Release
           uses: thedoctor0/zip-release@master
           with:
              filename: "release.zip"
              exclusions: "*.git*"
         - name: Upload Release
           uses: ncipollo/release-action@v1
           with:
              artifacts: "release.zip"
              token: ${{ secrets.GITHUB_TOKEN }}
         - name: 🚀 Install
           run: npm install
         - name: 🚀 Build
           run: npm run build
         - name: 🚀 publish
           run: npm publish --access public
           env:
              NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
